name = "NumericalSemigroupLab"
uuid = "7c8b7b9e-1234-5678-9abc-def012345678"
authors = ["blackgauss"]
version = "1.0.0"

[deps]

[compat]
julia = "1.9"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "BenchmarkTools"]
